src/models/Trabajos.py
from datetime import datetime
from src import db
from sqlalchemy.orm import relationship


class Trabajo(db.Model):
    __tablename__ = "trabajos"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False, unique=True)

    trabajoprecios = relationship("TrabajoPrecio", back_populates='trabajos')
    asignaciones = relationship("Asignacion", back_populates='trabajos')
    
    created = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    status = db.Column(db.Boolean, unique=False, default=True)

class TrabajoPrecio(db.Model):
    __tablename__ = "trabajoprecios"
    id = db.Column(db.Integer, primary_key=True)
    precio = db.Column(db.Integer, nullable=False)

    trabajo_id = db.Column(db.Integer, db.ForeignKey("trabajos.id"), nullable=False)
    trabajos = relationship("Trabajo", back_populates="trabajoprecios")

    asignaciones = relationship("Asignacion", back_populates='trabajoprecios')
    
    created = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    status = db.Column(db.Boolean, unique=False, default=True) 

src/views/trabajo.py
from flask import(
    render_template, Blueprint, flash, 
    redirect, request, url_for
)
from flask_login import login_required

from src import db

from src.models.Trabajos import Trabajo, TrabajoPrecio

from src.forms.pieza import PiezaForm

trabajo = Blueprint('trabajo', __name__, url_prefix='/trabajo')

@trabajo.route('')
@login_required
def index():
    trabajos = Trabajo.query.all()
    return render_template('/trabajo/index.html', trabajos=trabajos)

@trabajo.route('/create', methods=['POST'])
@login_required
def trabajo_create():
    if request.method == 'POST':
        name = request.form.get('name')
        trabajo = Trabajo.query.filter_by(name=name).first()
        if trabajo:
            flash('Error, El tipo de trabajo ya exicte!.')
            return redirect(url_for('trabajo.index'))
        else:
            save = Trabajo(name=name)
            db.session.add(save)
            db.session.commit()
            flash('registro con exicto!.')
            return redirect(url_for('trabajo.index'))
    return redirect(url_for('trabajo.index'))

@trabajo.route('/precio', methods=['POST'])
@login_required
def precio():
    if request.method == 'POST':
        try:
            t_precio = TrabajoPrecio()

            precio = request.form.get('precio')
            trabajo = int(request.form.get('trabajo'))

            get_precio = TrabajoPrecio.query.filter_by(trabajo_id=trabajo, precio=precio).first()


            if not trabajo:
                flash('Debe selecionar una trabajo')
                return redirect(url_for('trabajo.index'))
    
            if get_precio:
                flash('Precio no disponible')
                return redirect(url_for('trabajo.index'))

            t_precio.precio = precio
            t_precio.trabajo_id = trabajo

            db.session.add(t_precio)
            db.session.commit()
            flash('Registrada exitoso!.')
            return redirect(url_for('trabajo.index'))
        except Exception as e:
            print(e)
            flash('Error al intentar registrar los datos enviado')
            return redirect(url_for('trabajo.index'))


@trabajo.route('/delete/<int:id>', methods=['POST'])
def trabajo_delete(id):
    query_trabajo = Trabajo.query.filter_by(id=id).first()
    try:
        if not query_trabajo:
            flash("Error de servidor al intentar eliminar la query_trabajo")
            return redirect(url_for('trabajo.index'))    
        
        trabajo_precio = TrabajoPrecio.query.filter_by(trabajo_id=query_trabajo.id).all()

        if query_trabajo and not trabajo_precio:
            db.session.delete(query_trabajo)
            db.session.commit()
            flash('Nombre de trabajo eliminada')
            return redirect(url_for('trabajo.index'))

        if query_trabajo and trabajo_precio:
            for iten in trabajo_precio:
                db.session.delete(iten)
            db.session.delete(query_trabajo)
            db.session.commit()
            flash('trabajo y Precios eliminados')
            return redirect(url_for('trabajo.index'))
    except Exception as e:
        print(e)
        flash('Error al itentar eliminar')
        return redirect(url_for('.index'))

@trabajo.route('/delete/precio/<int:id>', methods=['POST'])
def precio_delete(id):
    trabajo_precio = TrabajoPrecio.query.filter_by(id=id).first()
    if not trabajo_precio:
        flash("Error de servidor al intentar eliminar el precio")
        return redirect(url_for('trabajo.index'))    

    db.session.delete(trabajo_precio)
    db.session.commit()
    flash('Precios eliminados')
    return redirect(url_for('trabajo.index'))



        
    

src/templates/trabajo/index.html
{% extends "layouts/base.html" %} {% block title %} UI Forms {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %} {% block content %}

<div class="pcoded-content">
  <div class="pcoded-inner-content">
    <!-- [ breadcrumb ] start -->
    <div class="page-header">
      <div class="page-block">
        <div class="row align-items-center">
          <div class="col-md-12">
            <div class="page-header-title">
              <h5 class="m-b-10">Area de registro de trabajos</h5>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- [ breadcrumb ] end -->
    <div class="main-body">
      <div class="page-wrapper">
        <!-- [ Main Content ] start -->
        <div class="row">
          <div class="col-md-6">
            <div class="card">
              <div class="card-header">
                <h5>Registro de tipos de trabajos</h5>
              </div>
              <div class="card-body">
                <div class="row">
                  <div class="col-md-8">
                    <form role="form" method="post" action="{{ url_for('trabajo.trabajo_create') }}">
                      <div class="form-group">
                        <input type="text" name="name" id="" class="form-control" />
                      </div>
                      <button type="submit" class="btn btn-primary">
                        enviar
                      </button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card">
              <div class="card-header">
                <h5>Registro de Precios</h5>
              </div>
              <div class="col-md-12">
                <form role="form" method="post" action="/trabajo/precio">
                  <div class="form-group">
                    <select class="form-control" id="modelo_create" name="trabajo">
                      <option value="">Seleciona un trabajo</option>
                      {% for trabajo in trabajos %}
                      <option value="{{trabajo.id}}">{{trabajo.name}}</option>
                      {% endfor %}
                    </select>
                  </div>
                  <div class="form-group">
                    <label>Precio</label>
                    <input type="number" class="form-control" name="precio" placeholder="Ingresa el precio" />
                  </div>
                  <button type="submit" class="btn btn-primary">enviar</button>
                </form>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="col-sm-12">
              <h5 class="mb-3">Lista de trabajos</h5>
              <hr />

              <div class="accordion">
                <div class="card">
                  {% for trabajo in trabajos %}
                  <div class="card-header">
                    <h5 class="mb-0">{{trabajo.name}}</h5>
                    <form action="/trabajo/delete/{{trabajo.id}}" method="post">
                      <input type="submit" class="badge-danger border-0 text-white" value="Eliminar">
                    </form>
                  </div>
                  <div class="card-body collapse show">
                    <ul>
                      {% for precio in trabajo.trabajoprecios %}
                      <li class="mb-0">
                        <h4>{{precio.precio}}  </h4>  <form action="/trabajo/delete/precio/{{precio.id}}" method="post">
                          <input type="submit" class="badge-danger  border-0 text-white" value="Eliminar" role="button">
                        </form>
                      </li>
                      {% endfor %}
                    </ul>
                  </div>
                  {% endfor %}
                </div>
              </div>
            </div>
          </div>

          <!-- [ collapse ] end -->
        </div>
        <!-- [ Main Content ] end -->
      </div>
    </div>
  </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}